# Pipeline Configuration

# Dataset and DataFrame settings
dataset:
  name: "Bingsu/Cat_and_Dog" # Name of the dataset
  split: "test"
  config_name: "full"
  class_name: "dog" # Name of the class
  main_subject: "dogs"
  captions_path: "data/captions.parquet" # Where to store the captions DataFrame
  assignments_path: "data/assignments.parquet" # Where to store the assignments DataFrame
  format: "parquet" # File format for storing DataFrames
  compression: "snappy" # Compression method for parquet files

# Pipeline stages settings
stages:
  caption_generation:
    batch_size: 3
  criteria_init:
    batch_size: 3
  criteria_refinement:
    num_rounds: 5
    sample_size: 4
